// lib: , url: package:logging/src/logger.dart

// class id: 1049338, size: 0x8
class :: {

  static late Level recordStackTraceAtLevel; // offset: 0xc88

  static Level recordStackTraceAtLevel() {
    // ** addr: 0x460d98, size: 0x8
    // 0x460d98: r0 = Instance_Level
    //     0x460d98: ldr             x0, [PP, #0x2e80]  ; [pp+0x2e80] Obj!Level@95cf21
    // 0x460d9c: ret
    //     0x460d9c: ret             
  }
}

// class id: 620, size: 0x1c, field offset: 0x8
class Logger extends Object {

  static late final Logger root; // offset: 0xc7c
  static late final Map<String, Logger> _loggers; // offset: 0xc80

  _ log(/* No info */) {
    // ** addr: 0x4604d4, size: 0x1b8
    // 0x4604d4: EnterFrame
    //     0x4604d4: stp             fp, lr, [SP, #-0x10]!
    //     0x4604d8: mov             fp, SP
    // 0x4604dc: AllocStack(0x30)
    //     0x4604dc: sub             SP, SP, #0x30
    // 0x4604e0: SetupParameters(Logger this /* r1 => r6, fp-0x10 */, dynamic _ /* r2 => r0, fp-0x18 */, dynamic _ /* r3 => r3, fp-0x20 */, dynamic _ /* r5 => r5, fp-0x28 */, [dynamic _ = Null /* r4, fp-0x8 */, dynamic _])
    //     0x4604e0: mov             x6, x1
    //     0x4604e4: mov             x0, x2
    //     0x4604e8: stur            x1, [fp, #-0x10]
    //     0x4604ec: stur            x2, [fp, #-0x18]
    //     0x4604f0: stur            x3, [fp, #-0x20]
    //     0x4604f4: stur            x5, [fp, #-0x28]
    //     0x4604f8: ldur            w1, [x4, #0x13]
    //     0x4604fc: sub             x2, x1, #8
    //     0x460500: cmp             w2, #2
    //     0x460504: b.lt            #0x460520
    //     0x460508: add             x1, fp, w2, sxtw #2
    //     0x46050c: ldr             x1, [x1, #8]
    //     0x460510: cmp             w2, #4
    //     0x460514: b.lt            #0x460524
    //     0x460518: mov             x4, x1
    //     0x46051c: b               #0x460528
    //     0x460520: mov             x1, NULL
    //     0x460524: mov             x4, x1
    //     0x460528: stur            x4, [fp, #-8]
    // 0x46052c: CheckStackOverflow
    //     0x46052c: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x460530: cmp             SP, x16
    //     0x460534: b.ls            #0x460684
    // 0x460538: mov             x1, x6
    // 0x46053c: mov             x2, x0
    // 0x460540: r0 = isLoggable()
    //     0x460540: bl              #0x460880  ; [package:logging/src/logger.dart] Logger::isLoggable
    // 0x460544: tbnz            w0, #4, #0x460674
    // 0x460548: ldur            x0, [fp, #-8]
    // 0x46054c: cmp             w0, NULL
    // 0x460550: b.eq            #0x460560
    // 0x460554: r16 = Instance__StringStackTrace
    //     0x460554: ldr             x16, [PP, #0x2010]  ; [pp+0x2010] Obj!_StringStackTrace@97c071
    // 0x460558: cmp             w0, w16
    // 0x46055c: b.ne            #0x4605f0
    // 0x460560: ldur            x2, [fp, #-0x18]
    // 0x460564: r0 = LoadStaticField(0xc88)
    //     0x460564: ldr             x0, [THR, #0x78]  ; THR::field_table_values
    //     0x460568: ldr             x0, [x0, #0x1910]
    // 0x46056c: ldr             x16, [THR, #0x90]  ; THR::object_sentinel
    // 0x460570: cmp             w0, w16
    // 0x460574: b.ne            #0x460580
    // 0x460578: r2 = recordStackTraceAtLevel
    //     0x460578: ldr             x2, [PP, #0x2e18]  ; [pp+0x2e18] Field <::.recordStackTraceAtLevel>: static late (offset: 0xc88)
    // 0x46057c: r0 = InitLateStaticField()
    //     0x46057c: bl              #0x933cf0  ; InitLateStaticFieldStub
    // 0x460580: ldur            x2, [fp, #-0x18]
    // 0x460584: LoadField: r0 = r2->field_b
    //     0x460584: ldur            x0, [x2, #0xb]
    // 0x460588: cmp             x0, #0x7d0
    // 0x46058c: b.lt            #0x4605e8
    // 0x460590: ldur            x0, [fp, #-0x28]
    // 0x460594: r0 = current()
    //     0x460594: bl              #0x3da85c  ; [dart:core] StackTrace::current
    // 0x460598: ldur            x0, [fp, #-0x28]
    // 0x46059c: cmp             w0, NULL
    // 0x4605a0: b.ne            #0x4605e0
    // 0x4605a4: ldur            x0, [fp, #-0x18]
    // 0x4605a8: ldur            x3, [fp, #-0x20]
    // 0x4605ac: r1 = Null
    //     0x4605ac: mov             x1, NULL
    // 0x4605b0: r2 = 8
    //     0x4605b0: movz            x2, #0x8
    // 0x4605b4: r0 = AllocateArray()
    //     0x4605b4: bl              #0x935bc4  ; AllocateArrayStub
    // 0x4605b8: r16 = "autogenerated stack trace for "
    //     0x4605b8: ldr             x16, [PP, #0x2e20]  ; [pp+0x2e20] "autogenerated stack trace for "
    // 0x4605bc: StoreField: r0->field_f = r16
    //     0x4605bc: stur            w16, [x0, #0xf]
    // 0x4605c0: ldur            x2, [fp, #-0x18]
    // 0x4605c4: StoreField: r0->field_13 = r2
    //     0x4605c4: stur            w2, [x0, #0x13]
    // 0x4605c8: r16 = " "
    //     0x4605c8: ldr             x16, [PP, #0x1aa0]  ; [pp+0x1aa0] " "
    // 0x4605cc: ArrayStore: r0[0] = r16  ; List_4
    //     0x4605cc: stur            w16, [x0, #0x17]
    // 0x4605d0: ldur            x3, [fp, #-0x20]
    // 0x4605d4: StoreField: r0->field_1b = r3
    //     0x4605d4: stur            w3, [x0, #0x1b]
    // 0x4605d8: str             x0, [SP]
    // 0x4605dc: r0 = _interpolate()
    //     0x4605dc: bl              #0x3cae24  ; [dart:core] _StringBase::_interpolate
    // 0x4605e0: mov             x6, x0
    // 0x4605e4: b               #0x4605f8
    // 0x4605e8: ldur            x0, [fp, #-0x28]
    // 0x4605ec: b               #0x4605f4
    // 0x4605f0: ldur            x0, [fp, #-0x28]
    // 0x4605f4: mov             x6, x0
    // 0x4605f8: ldur            x1, [fp, #-0x10]
    // 0x4605fc: stur            x6, [fp, #-8]
    // 0x460600: r0 = LoadStaticField(0x364)
    //     0x460600: ldr             x0, [THR, #0x78]  ; THR::field_table_values
    //     0x460604: ldr             x0, [x0, #0x6c8]
    // 0x460608: ldr             x16, [THR, #0x90]  ; THR::object_sentinel
    // 0x46060c: cmp             w0, w16
    // 0x460610: b.ne            #0x46061c
    // 0x460614: r2 = _current
    //     0x460614: ldr             x2, [PP, #0x208]  ; [pp+0x208] Field <Zone._current@5048458>: static late (offset: 0x364)
    // 0x460618: r0 = InitLateStaticField()
    //     0x460618: bl              #0x933cf0  ; InitLateStaticFieldStub
    // 0x46061c: ldur            x1, [fp, #-0x10]
    // 0x460620: r0 = fullName()
    //     0x460620: bl              #0x4607b0  ; [package:logging/src/logger.dart] Logger::fullName
    // 0x460624: stur            x0, [fp, #-0x28]
    // 0x460628: r0 = LogRecord()
    //     0x460628: bl              #0x4607a4  ; AllocateLogRecordStub -> LogRecord (size=0x18)
    // 0x46062c: mov             x1, x0
    // 0x460630: ldur            x2, [fp, #-0x18]
    // 0x460634: ldur            x3, [fp, #-0x20]
    // 0x460638: ldur            x5, [fp, #-0x28]
    // 0x46063c: ldur            x6, [fp, #-8]
    // 0x460640: r0 = LogRecord()
    //     0x460640: bl              #0x4606ac  ; [package:logging/src/log_record.dart] LogRecord::LogRecord
    // 0x460644: ldur            x0, [fp, #-0x10]
    // 0x460648: LoadField: r1 = r0->field_b
    //     0x460648: ldur            w1, [x0, #0xb]
    // 0x46064c: DecompressPointer r1
    //     0x46064c: add             x1, x1, HEAP, lsl #32
    // 0x460650: cmp             w1, NULL
    // 0x460654: b.eq            #0x460674
    // 0x460658: r0 = LoadStaticField(0xc7c)
    //     0x460658: ldr             x0, [THR, #0x78]  ; THR::field_table_values
    //     0x46065c: ldr             x0, [x0, #0x18f8]
    // 0x460660: ldr             x16, [THR, #0x90]  ; THR::object_sentinel
    // 0x460664: cmp             w0, w16
    // 0x460668: b.ne            #0x460674
    // 0x46066c: r2 = root
    //     0x46066c: ldr             x2, [PP, #0x2e28]  ; [pp+0x2e28] Field <Logger.root>: static late final (offset: 0xc7c)
    // 0x460670: r0 = InitLateFinalStaticField()
    //     0x460670: bl              #0x933c88  ; InitLateFinalStaticFieldStub
    // 0x460674: r0 = Null
    //     0x460674: mov             x0, NULL
    // 0x460678: LeaveFrame
    //     0x460678: mov             SP, fp
    //     0x46067c: ldp             fp, lr, [SP], #0x10
    // 0x460680: ret
    //     0x460680: ret             
    // 0x460684: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460684: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460688: b               #0x460538
  }
  get _ fullName(/* No info */) {
    // ** addr: 0x4607b0, size: 0xd0
    // 0x4607b0: EnterFrame
    //     0x4607b0: stp             fp, lr, [SP, #-0x10]!
    //     0x4607b4: mov             fp, SP
    // 0x4607b8: AllocStack(0x18)
    //     0x4607b8: sub             SP, SP, #0x18
    // 0x4607bc: SetupParameters(Logger this /* r1 => r0, fp-0x8 */)
    //     0x4607bc: mov             x0, x1
    //     0x4607c0: stur            x1, [fp, #-8]
    // 0x4607c4: CheckStackOverflow
    //     0x4607c4: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x4607c8: cmp             SP, x16
    //     0x4607cc: b.ls            #0x460874
    // 0x4607d0: LoadField: r1 = r0->field_b
    //     0x4607d0: ldur            w1, [x0, #0xb]
    // 0x4607d4: DecompressPointer r1
    //     0x4607d4: add             x1, x1, HEAP, lsl #32
    // 0x4607d8: cmp             w1, NULL
    // 0x4607dc: b.ne            #0x4607e8
    // 0x4607e0: r2 = Null
    //     0x4607e0: mov             x2, NULL
    // 0x4607e4: b               #0x460804
    // 0x4607e8: LoadField: r2 = r1->field_7
    //     0x4607e8: ldur            w2, [x1, #7]
    // 0x4607ec: DecompressPointer r2
    //     0x4607ec: add             x2, x2, HEAP, lsl #32
    // 0x4607f0: LoadField: r3 = r2->field_7
    //     0x4607f0: ldur            w3, [x2, #7]
    // 0x4607f4: cbnz            w3, #0x460800
    // 0x4607f8: r2 = false
    //     0x4607f8: add             x2, NULL, #0x30  ; false
    // 0x4607fc: b               #0x460804
    // 0x460800: r2 = true
    //     0x460800: add             x2, NULL, #0x20  ; true
    // 0x460804: cmp             w2, NULL
    // 0x460808: b.eq            #0x46085c
    // 0x46080c: tbnz            w2, #4, #0x46085c
    // 0x460810: cmp             w1, NULL
    // 0x460814: b.eq            #0x46087c
    // 0x460818: r0 = fullName()
    //     0x460818: bl              #0x4607b0  ; [package:logging/src/logger.dart] Logger::fullName
    // 0x46081c: r1 = Null
    //     0x46081c: mov             x1, NULL
    // 0x460820: r2 = 6
    //     0x460820: movz            x2, #0x6
    // 0x460824: stur            x0, [fp, #-0x10]
    // 0x460828: r0 = AllocateArray()
    //     0x460828: bl              #0x935bc4  ; AllocateArrayStub
    // 0x46082c: mov             x1, x0
    // 0x460830: ldur            x0, [fp, #-0x10]
    // 0x460834: StoreField: r1->field_f = r0
    //     0x460834: stur            w0, [x1, #0xf]
    // 0x460838: r16 = "."
    //     0x460838: ldr             x16, [PP, #0x90]  ; [pp+0x90] "."
    // 0x46083c: StoreField: r1->field_13 = r16
    //     0x46083c: stur            w16, [x1, #0x13]
    // 0x460840: ldur            x0, [fp, #-8]
    // 0x460844: LoadField: r2 = r0->field_7
    //     0x460844: ldur            w2, [x0, #7]
    // 0x460848: DecompressPointer r2
    //     0x460848: add             x2, x2, HEAP, lsl #32
    // 0x46084c: ArrayStore: r1[0] = r2  ; List_4
    //     0x46084c: stur            w2, [x1, #0x17]
    // 0x460850: str             x1, [SP]
    // 0x460854: r0 = _interpolate()
    //     0x460854: bl              #0x3cae24  ; [dart:core] _StringBase::_interpolate
    // 0x460858: b               #0x460868
    // 0x46085c: LoadField: r1 = r0->field_7
    //     0x46085c: ldur            w1, [x0, #7]
    // 0x460860: DecompressPointer r1
    //     0x460860: add             x1, x1, HEAP, lsl #32
    // 0x460864: mov             x0, x1
    // 0x460868: LeaveFrame
    //     0x460868: mov             SP, fp
    //     0x46086c: ldp             fp, lr, [SP], #0x10
    // 0x460870: ret
    //     0x460870: ret             
    // 0x460874: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460874: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460878: b               #0x4607d0
    // 0x46087c: r0 = NullCastErrorSharedWithoutFPURegs()
    //     0x46087c: bl              #0x936360  ; NullCastErrorSharedWithoutFPURegsStub
  }
  _ isLoggable(/* No info */) {
    // ** addr: 0x460880, size: 0x4c
    // 0x460880: EnterFrame
    //     0x460880: stp             fp, lr, [SP, #-0x10]!
    //     0x460884: mov             fp, SP
    // 0x460888: AllocStack(0x8)
    //     0x460888: sub             SP, SP, #8
    // 0x46088c: SetupParameters(dynamic _ /* r2 => r2, fp-0x8 */)
    //     0x46088c: stur            x2, [fp, #-8]
    // 0x460890: CheckStackOverflow
    //     0x460890: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x460894: cmp             SP, x16
    //     0x460898: b.ls            #0x4608c4
    // 0x46089c: r0 = level()
    //     0x46089c: bl              #0x4608cc  ; [package:logging/src/logger.dart] Logger::level
    // 0x4608a0: ldur            x1, [fp, #-8]
    // 0x4608a4: LoadField: r2 = r1->field_b
    //     0x4608a4: ldur            x2, [x1, #0xb]
    // 0x4608a8: cmp             x2, #0x320
    // 0x4608ac: r16 = true
    //     0x4608ac: add             x16, NULL, #0x20  ; true
    // 0x4608b0: r17 = false
    //     0x4608b0: add             x17, NULL, #0x30  ; false
    // 0x4608b4: csel            x0, x16, x17, ge
    // 0x4608b8: LeaveFrame
    //     0x4608b8: mov             SP, fp
    //     0x4608bc: ldp             fp, lr, [SP], #0x10
    // 0x4608c0: ret
    //     0x4608c0: ret             
    // 0x4608c4: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x4608c4: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x4608c8: b               #0x46089c
  }
  get _ level(/* No info */) {
    // ** addr: 0x4608cc, size: 0x84
    // 0x4608cc: EnterFrame
    //     0x4608cc: stp             fp, lr, [SP, #-0x10]!
    //     0x4608d0: mov             fp, SP
    // 0x4608d4: CheckStackOverflow
    //     0x4608d4: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x4608d8: cmp             SP, x16
    //     0x4608dc: b.ls            #0x460940
    // 0x4608e0: LoadField: r0 = r1->field_b
    //     0x4608e0: ldur            w0, [x1, #0xb]
    // 0x4608e4: DecompressPointer r0
    //     0x4608e4: add             x0, x0, HEAP, lsl #32
    // 0x4608e8: cmp             w0, NULL
    // 0x4608ec: b.ne            #0x460904
    // 0x4608f0: LoadField: r0 = r1->field_f
    //     0x4608f0: ldur            w0, [x1, #0xf]
    // 0x4608f4: DecompressPointer r0
    //     0x4608f4: add             x0, x0, HEAP, lsl #32
    // 0x4608f8: cmp             w0, NULL
    // 0x4608fc: b.eq            #0x460948
    // 0x460900: b               #0x460934
    // 0x460904: r0 = LoadStaticField(0xc7c)
    //     0x460904: ldr             x0, [THR, #0x78]  ; THR::field_table_values
    //     0x460908: ldr             x0, [x0, #0x18f8]
    // 0x46090c: ldr             x16, [THR, #0x90]  ; THR::object_sentinel
    // 0x460910: cmp             w0, w16
    // 0x460914: b.ne            #0x460920
    // 0x460918: r2 = root
    //     0x460918: ldr             x2, [PP, #0x2e28]  ; [pp+0x2e28] Field <Logger.root>: static late final (offset: 0xc7c)
    // 0x46091c: r0 = InitLateFinalStaticField()
    //     0x46091c: bl              #0x933c88  ; InitLateFinalStaticFieldStub
    // 0x460920: LoadField: r1 = r0->field_f
    //     0x460920: ldur            w1, [x0, #0xf]
    // 0x460924: DecompressPointer r1
    //     0x460924: add             x1, x1, HEAP, lsl #32
    // 0x460928: cmp             w1, NULL
    // 0x46092c: b.eq            #0x46094c
    // 0x460930: mov             x0, x1
    // 0x460934: LeaveFrame
    //     0x460934: mov             SP, fp
    //     0x460938: ldp             fp, lr, [SP], #0x10
    // 0x46093c: ret
    //     0x46093c: ret             
    // 0x460940: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460940: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460944: b               #0x4608e0
    // 0x460948: r0 = NullCastErrorSharedWithoutFPURegs()
    //     0x460948: bl              #0x936360  ; NullCastErrorSharedWithoutFPURegsStub
    // 0x46094c: r0 = NullCastErrorSharedWithoutFPURegs()
    //     0x46094c: bl              #0x936360  ; NullCastErrorSharedWithoutFPURegsStub
  }
  static Logger root() {
    // ** addr: 0x460950, size: 0x34
    // 0x460950: EnterFrame
    //     0x460950: stp             fp, lr, [SP, #-0x10]!
    //     0x460954: mov             fp, SP
    // 0x460958: CheckStackOverflow
    //     0x460958: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x46095c: cmp             SP, x16
    //     0x460960: b.ls            #0x46097c
    // 0x460964: r1 = Null
    //     0x460964: mov             x1, NULL
    // 0x460968: r2 = ""
    //     0x460968: ldr             x2, [PP, #0x88]  ; [pp+0x88] ""
    // 0x46096c: r0 = Logger()
    //     0x46096c: bl              #0x460984  ; [package:logging/src/logger.dart] Logger::Logger
    // 0x460970: LeaveFrame
    //     0x460970: mov             SP, fp
    //     0x460974: ldp             fp, lr, [SP], #0x10
    // 0x460978: ret
    //     0x460978: ret             
    // 0x46097c: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x46097c: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460980: b               #0x460964
  }
  factory _ Logger(/* No info */) {
    // ** addr: 0x460984, size: 0x90
    // 0x460984: EnterFrame
    //     0x460984: stp             fp, lr, [SP, #-0x10]!
    //     0x460988: mov             fp, SP
    // 0x46098c: AllocStack(0x18)
    //     0x46098c: sub             SP, SP, #0x18
    // 0x460990: SetupParameters(dynamic _ /* r2 => r2, fp-0x8 */)
    //     0x460990: stur            x2, [fp, #-8]
    // 0x460994: CheckStackOverflow
    //     0x460994: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x460998: cmp             SP, x16
    //     0x46099c: b.ls            #0x460a0c
    // 0x4609a0: r1 = 1
    //     0x4609a0: movz            x1, #0x1
    // 0x4609a4: r0 = AllocateContext()
    //     0x4609a4: bl              #0x934ad4  ; AllocateContextStub
    // 0x4609a8: mov             x1, x0
    // 0x4609ac: ldur            x0, [fp, #-8]
    // 0x4609b0: stur            x1, [fp, #-0x10]
    // 0x4609b4: StoreField: r1->field_f = r0
    //     0x4609b4: stur            w0, [x1, #0xf]
    // 0x4609b8: r0 = LoadStaticField(0xc80)
    //     0x4609b8: ldr             x0, [THR, #0x78]  ; THR::field_table_values
    //     0x4609bc: ldr             x0, [x0, #0x1900]
    // 0x4609c0: ldr             x16, [THR, #0x90]  ; THR::object_sentinel
    // 0x4609c4: cmp             w0, w16
    // 0x4609c8: b.ne            #0x4609d4
    // 0x4609cc: r2 = _loggers
    //     0x4609cc: ldr             x2, [PP, #0x2e50]  ; [pp+0x2e50] Field <Logger._loggers@856512371>: static late final (offset: 0xc80)
    // 0x4609d0: r0 = InitLateFinalStaticField()
    //     0x4609d0: bl              #0x933c88  ; InitLateFinalStaticFieldStub
    // 0x4609d4: ldur            x2, [fp, #-0x10]
    // 0x4609d8: stur            x0, [fp, #-0x18]
    // 0x4609dc: LoadField: r3 = r2->field_f
    //     0x4609dc: ldur            w3, [x2, #0xf]
    // 0x4609e0: DecompressPointer r3
    //     0x4609e0: add             x3, x3, HEAP, lsl #32
    // 0x4609e4: stur            x3, [fp, #-8]
    // 0x4609e8: r1 = Function '<anonymous closure>': static.
    //     0x4609e8: ldr             x1, [PP, #0x2e58]  ; [pp+0x2e58] AnonymousClosure: static (0x460a14), in [package:logging/src/logger.dart] Logger::Logger (0x460984)
    // 0x4609ec: r0 = AllocateClosure()
    //     0x4609ec: bl              #0x934ea8  ; AllocateClosureStub
    // 0x4609f0: ldur            x1, [fp, #-0x18]
    // 0x4609f4: ldur            x2, [fp, #-8]
    // 0x4609f8: mov             x3, x0
    // 0x4609fc: r0 = putIfAbsent()
    //     0x4609fc: bl              #0x822f50  ; [dart:_compact_hash] __Map&_HashVMBase&MapMixin&_HashBase&_OperatorEqualsAndHashCode&_LinkedHashMapMixin::putIfAbsent
    // 0x460a00: LeaveFrame
    //     0x460a00: mov             SP, fp
    //     0x460a04: ldp             fp, lr, [SP], #0x10
    // 0x460a08: ret
    //     0x460a08: ret             
    // 0x460a0c: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460a0c: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460a10: b               #0x4609a0
  }
  [closure] static Logger <anonymous closure>(dynamic) {
    // ** addr: 0x460a14, size: 0x44
    // 0x460a14: EnterFrame
    //     0x460a14: stp             fp, lr, [SP, #-0x10]!
    //     0x460a18: mov             fp, SP
    // 0x460a1c: ldr             x0, [fp, #0x10]
    // 0x460a20: ArrayLoad: r1 = r0[0]  ; List_4
    //     0x460a20: ldur            w1, [x0, #0x17]
    // 0x460a24: DecompressPointer r1
    //     0x460a24: add             x1, x1, HEAP, lsl #32
    // 0x460a28: CheckStackOverflow
    //     0x460a28: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x460a2c: cmp             SP, x16
    //     0x460a30: b.ls            #0x460a50
    // 0x460a34: LoadField: r2 = r1->field_f
    //     0x460a34: ldur            w2, [x1, #0xf]
    // 0x460a38: DecompressPointer r2
    //     0x460a38: add             x2, x2, HEAP, lsl #32
    // 0x460a3c: r1 = Null
    //     0x460a3c: mov             x1, NULL
    // 0x460a40: r0 = Logger._named()
    //     0x460a40: bl              #0x460a58  ; [package:logging/src/logger.dart] Logger::Logger._named
    // 0x460a44: LeaveFrame
    //     0x460a44: mov             SP, fp
    //     0x460a48: ldp             fp, lr, [SP], #0x10
    // 0x460a4c: ret
    //     0x460a4c: ret             
    // 0x460a50: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460a50: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460a54: b               #0x460a34
  }
  factory _ Logger._named(/* No info */) {
    // ** addr: 0x460a58, size: 0x20c
    // 0x460a58: EnterFrame
    //     0x460a58: stp             fp, lr, [SP, #-0x10]!
    //     0x460a5c: mov             fp, SP
    // 0x460a60: AllocStack(0x38)
    //     0x460a60: sub             SP, SP, #0x38
    // 0x460a64: SetupParameters(dynamic _ /* r2 => r0, fp-0x8 */)
    //     0x460a64: mov             x0, x2
    //     0x460a68: stur            x2, [fp, #-8]
    // 0x460a6c: CheckStackOverflow
    //     0x460a6c: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x460a70: cmp             SP, x16
    //     0x460a74: b.ls            #0x460c54
    // 0x460a78: mov             x1, x0
    // 0x460a7c: r2 = "."
    //     0x460a7c: ldr             x2, [PP, #0x90]  ; [pp+0x90] "."
    // 0x460a80: r4 = const [0, 0x2, 0, 0x2, null]
    //     0x460a80: ldr             x4, [PP, #0x258]  ; [pp+0x258] List(5) [0, 0x2, 0, 0x2, Null]
    // 0x460a84: r0 = startsWith()
    //     0x460a84: bl              #0x3d37d0  ; [dart:core] _StringBase::startsWith
    // 0x460a88: tbz             w0, #4, #0x460c08
    // 0x460a8c: ldur            x0, [fp, #-8]
    // 0x460a90: LoadField: r1 = r0->field_7
    //     0x460a90: ldur            w1, [x0, #7]
    // 0x460a94: r2 = LoadInt32Instr(r1)
    //     0x460a94: sbfx            x2, x1, #1, #0x1f
    // 0x460a98: sub             x1, x2, #1
    // 0x460a9c: stur            x1, [fp, #-0x10]
    // 0x460aa0: lsl             x2, x1, #1
    // 0x460aa4: stp             x2, x0, [SP, #8]
    // 0x460aa8: r16 = "."
    //     0x460aa8: ldr             x16, [PP, #0x90]  ; [pp+0x90] "."
    // 0x460aac: str             x16, [SP]
    // 0x460ab0: r0 = _substringMatches()
    //     0x460ab0: bl              #0x3d3920  ; [dart:core] _StringBase::_substringMatches
    // 0x460ab4: tbz             w0, #4, #0x460c2c
    // 0x460ab8: ldur            x2, [fp, #-0x10]
    // 0x460abc: stur            x2, [fp, #-0x10]
    // 0x460ac0: CheckStackOverflow
    //     0x460ac0: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x460ac4: cmp             SP, x16
    //     0x460ac8: b.ls            #0x460c5c
    // 0x460acc: tbnz            x2, #0x3f, #0x460b14
    // 0x460ad0: r0 = BoxInt64Instr(r2)
    //     0x460ad0: sbfiz           x0, x2, #1, #0x1f
    //     0x460ad4: cmp             x2, x0, asr #1
    //     0x460ad8: b.eq            #0x460ae4
    //     0x460adc: bl              #0x935e50  ; AllocateMintSharedWithoutFPURegsStub
    //     0x460ae0: stur            x2, [x0, #7]
    // 0x460ae4: ldur            x16, [fp, #-8]
    // 0x460ae8: stp             x0, x16, [SP, #8]
    // 0x460aec: r16 = "."
    //     0x460aec: ldr             x16, [PP, #0x90]  ; [pp+0x90] "."
    // 0x460af0: str             x16, [SP]
    // 0x460af4: r0 = _substringMatches()
    //     0x460af4: bl              #0x3d3920  ; [dart:core] _StringBase::_substringMatches
    // 0x460af8: tbz             w0, #4, #0x460b08
    // 0x460afc: ldur            x0, [fp, #-0x10]
    // 0x460b00: sub             x2, x0, #1
    // 0x460b04: b               #0x460abc
    // 0x460b08: ldur            x0, [fp, #-0x10]
    // 0x460b0c: mov             x3, x0
    // 0x460b10: b               #0x460b18
    // 0x460b14: r3 = -1
    //     0x460b14: movn            x3, #0
    // 0x460b18: stur            x3, [fp, #-0x10]
    // 0x460b1c: cmn             x3, #1
    // 0x460b20: b.ne            #0x460b68
    // 0x460b24: ldur            x1, [fp, #-8]
    // 0x460b28: r0 = LoadClassIdInstr(r1)
    //     0x460b28: ldur            x0, [x1, #-1]
    //     0x460b2c: ubfx            x0, x0, #0xc, #0x14
    // 0x460b30: r16 = ""
    //     0x460b30: ldr             x16, [PP, #0x88]  ; [pp+0x88] ""
    // 0x460b34: stp             x16, x1, [SP]
    // 0x460b38: mov             lr, x0
    // 0x460b3c: ldr             lr, [x21, lr, lsl #3]
    // 0x460b40: blr             lr
    // 0x460b44: tbz             w0, #4, #0x460b58
    // 0x460b48: r1 = Null
    //     0x460b48: mov             x1, NULL
    // 0x460b4c: r2 = ""
    //     0x460b4c: ldr             x2, [PP, #0x88]  ; [pp+0x88] ""
    // 0x460b50: r0 = Logger()
    //     0x460b50: bl              #0x460984  ; [package:logging/src/logger.dart] Logger::Logger
    // 0x460b54: b               #0x460b5c
    // 0x460b58: r0 = Null
    //     0x460b58: mov             x0, NULL
    // 0x460b5c: mov             x3, x0
    // 0x460b60: ldur            x2, [fp, #-8]
    // 0x460b64: b               #0x460bc0
    // 0x460b68: r0 = BoxInt64Instr(r3)
    //     0x460b68: sbfiz           x0, x3, #1, #0x1f
    //     0x460b6c: cmp             x3, x0, asr #1
    //     0x460b70: b.eq            #0x460b7c
    //     0x460b74: bl              #0x935e50  ; AllocateMintSharedWithoutFPURegsStub
    //     0x460b78: stur            x3, [x0, #7]
    // 0x460b7c: str             x0, [SP]
    // 0x460b80: ldur            x1, [fp, #-8]
    // 0x460b84: r2 = 0
    //     0x460b84: movz            x2, #0
    // 0x460b88: r4 = const [0, 0x3, 0x1, 0x3, null]
    //     0x460b88: ldr             x4, [PP, #0x260]  ; [pp+0x260] List(5) [0, 0x3, 0x1, 0x3, Null]
    // 0x460b8c: r0 = substring()
    //     0x460b8c: bl              #0x3cd308  ; [dart:core] _StringBase::substring
    // 0x460b90: mov             x2, x0
    // 0x460b94: r1 = Null
    //     0x460b94: mov             x1, NULL
    // 0x460b98: r0 = Logger()
    //     0x460b98: bl              #0x460984  ; [package:logging/src/logger.dart] Logger::Logger
    // 0x460b9c: mov             x3, x0
    // 0x460ba0: ldur            x0, [fp, #-0x10]
    // 0x460ba4: stur            x3, [fp, #-0x18]
    // 0x460ba8: add             x2, x0, #1
    // 0x460bac: ldur            x1, [fp, #-8]
    // 0x460bb0: r4 = const [0, 0x2, 0, 0x2, null]
    //     0x460bb0: ldr             x4, [PP, #0x258]  ; [pp+0x258] List(5) [0, 0x2, 0, 0x2, Null]
    // 0x460bb4: r0 = substring()
    //     0x460bb4: bl              #0x3cd308  ; [dart:core] _StringBase::substring
    // 0x460bb8: ldur            x3, [fp, #-0x18]
    // 0x460bbc: mov             x2, x0
    // 0x460bc0: stur            x3, [fp, #-8]
    // 0x460bc4: stur            x2, [fp, #-0x18]
    // 0x460bc8: r16 = <String, Logger>
    //     0x460bc8: ldr             x16, [PP, #0x2e60]  ; [pp+0x2e60] TypeArguments: <String, Logger>
    // 0x460bcc: ldr             lr, [THR, #0xa8]  ; THR::empty_array
    // 0x460bd0: stp             lr, x16, [SP]
    // 0x460bd4: r0 = Map._fromLiteral()
    //     0x460bd4: bl              #0x3d907c  ; [dart:core] Map::Map._fromLiteral
    // 0x460bd8: stur            x0, [fp, #-0x20]
    // 0x460bdc: r0 = Logger()
    //     0x460bdc: bl              #0x460d50  ; AllocateLoggerStub -> Logger (size=0x1c)
    // 0x460be0: mov             x1, x0
    // 0x460be4: ldur            x2, [fp, #-0x18]
    // 0x460be8: ldur            x3, [fp, #-8]
    // 0x460bec: ldur            x5, [fp, #-0x20]
    // 0x460bf0: stur            x0, [fp, #-8]
    // 0x460bf4: r0 = Logger._internal()
    //     0x460bf4: bl              #0x460c64  ; [package:logging/src/logger.dart] Logger::Logger._internal
    // 0x460bf8: ldur            x0, [fp, #-8]
    // 0x460bfc: LeaveFrame
    //     0x460bfc: mov             SP, fp
    //     0x460c00: ldp             fp, lr, [SP], #0x10
    // 0x460c04: ret
    //     0x460c04: ret             
    // 0x460c08: r0 = ArgumentError()
    //     0x460c08: bl              #0x3cac5c  ; AllocateArgumentErrorStub -> ArgumentError (size=0x1c)
    // 0x460c0c: mov             x1, x0
    // 0x460c10: r0 = "name shouldn\'t start with a \'.\'"
    //     0x460c10: ldr             x0, [PP, #0x2e68]  ; [pp+0x2e68] "name shouldn\'t start with a \'.\'"
    // 0x460c14: ArrayStore: r1[0] = r0  ; List_4
    //     0x460c14: stur            w0, [x1, #0x17]
    // 0x460c18: r0 = false
    //     0x460c18: add             x0, NULL, #0x30  ; false
    // 0x460c1c: StoreField: r1->field_b = r0
    //     0x460c1c: stur            w0, [x1, #0xb]
    // 0x460c20: mov             x0, x1
    // 0x460c24: r0 = Throw()
    //     0x460c24: bl              #0x933dc8  ; ThrowStub
    // 0x460c28: brk             #0
    // 0x460c2c: r0 = false
    //     0x460c2c: add             x0, NULL, #0x30  ; false
    // 0x460c30: r0 = ArgumentError()
    //     0x460c30: bl              #0x3cac5c  ; AllocateArgumentErrorStub -> ArgumentError (size=0x1c)
    // 0x460c34: mov             x1, x0
    // 0x460c38: r0 = "name shouldn\'t end with a \'.\'"
    //     0x460c38: ldr             x0, [PP, #0x2e70]  ; [pp+0x2e70] "name shouldn\'t end with a \'.\'"
    // 0x460c3c: ArrayStore: r1[0] = r0  ; List_4
    //     0x460c3c: stur            w0, [x1, #0x17]
    // 0x460c40: r0 = false
    //     0x460c40: add             x0, NULL, #0x30  ; false
    // 0x460c44: StoreField: r1->field_b = r0
    //     0x460c44: stur            w0, [x1, #0xb]
    // 0x460c48: mov             x0, x1
    // 0x460c4c: r0 = Throw()
    //     0x460c4c: bl              #0x933dc8  ; ThrowStub
    // 0x460c50: brk             #0
    // 0x460c54: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460c54: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460c58: b               #0x460a78
    // 0x460c5c: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460c5c: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460c60: b               #0x460acc
  }
  _ Logger._internal(/* No info */) {
    // ** addr: 0x460c64, size: 0xec
    // 0x460c64: EnterFrame
    //     0x460c64: stp             fp, lr, [SP, #-0x10]!
    //     0x460c68: mov             fp, SP
    // 0x460c6c: AllocStack(0x18)
    //     0x460c6c: sub             SP, SP, #0x18
    // 0x460c70: SetupParameters(Logger this /* r1 => r4, fp-0x10 */, dynamic _ /* r2 => r3, fp-0x18 */, dynamic _ /* r3 => r2 */)
    //     0x460c70: mov             x4, x1
    //     0x460c74: stur            x2, [fp, #-0x18]
    //     0x460c78: mov             x16, x3
    //     0x460c7c: mov             x3, x2
    //     0x460c80: mov             x2, x16
    //     0x460c84: stur            x1, [fp, #-0x10]
    //     0x460c88: mov             x1, x5
    // 0x460c8c: CheckStackOverflow
    //     0x460c8c: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x460c90: cmp             SP, x16
    //     0x460c94: b.ls            #0x460d48
    // 0x460c98: mov             x0, x3
    // 0x460c9c: StoreField: r4->field_7 = r0
    //     0x460c9c: stur            w0, [x4, #7]
    //     0x460ca0: ldurb           w16, [x4, #-1]
    //     0x460ca4: ldurb           w17, [x0, #-1]
    //     0x460ca8: and             x16, x17, x16, lsr #2
    //     0x460cac: tst             x16, HEAP, lsr #32
    //     0x460cb0: b.eq            #0x460cb8
    //     0x460cb4: bl              #0x934290  ; WriteBarrierWrappersStub
    // 0x460cb8: mov             x0, x2
    // 0x460cbc: StoreField: r4->field_b = r0
    //     0x460cbc: stur            w0, [x4, #0xb]
    //     0x460cc0: ldurb           w16, [x4, #-1]
    //     0x460cc4: ldurb           w17, [x0, #-1]
    //     0x460cc8: and             x16, x17, x16, lsr #2
    //     0x460ccc: tst             x16, HEAP, lsr #32
    //     0x460cd0: b.eq            #0x460cd8
    //     0x460cd4: bl              #0x934290  ; WriteBarrierWrappersStub
    // 0x460cd8: mov             x0, x1
    // 0x460cdc: StoreField: r4->field_13 = r0
    //     0x460cdc: stur            w0, [x4, #0x13]
    //     0x460ce0: ldurb           w16, [x4, #-1]
    //     0x460ce4: ldurb           w17, [x0, #-1]
    //     0x460ce8: and             x16, x17, x16, lsr #2
    //     0x460cec: tst             x16, HEAP, lsr #32
    //     0x460cf0: b.eq            #0x460cf8
    //     0x460cf4: bl              #0x934290  ; WriteBarrierWrappersStub
    // 0x460cf8: cmp             w2, NULL
    // 0x460cfc: b.ne            #0x460d0c
    // 0x460d00: r0 = Instance_Level
    //     0x460d00: ldr             x0, [PP, #0x2e78]  ; [pp+0x2e78] Obj!Level@95cf01
    // 0x460d04: StoreField: r4->field_f = r0
    //     0x460d04: stur            w0, [x4, #0xf]
    // 0x460d08: b               #0x460d38
    // 0x460d0c: LoadField: r0 = r2->field_13
    //     0x460d0c: ldur            w0, [x2, #0x13]
    // 0x460d10: DecompressPointer r0
    //     0x460d10: add             x0, x0, HEAP, lsl #32
    // 0x460d14: mov             x1, x0
    // 0x460d18: mov             x2, x3
    // 0x460d1c: stur            x0, [fp, #-8]
    // 0x460d20: r0 = _hashCode()
    //     0x460d20: bl              #0x92c9d0  ; [dart:_compact_hash] __Map&_HashVMBase&MapMixin&_HashBase&_OperatorEqualsAndHashCode::_hashCode
    // 0x460d24: ldur            x1, [fp, #-8]
    // 0x460d28: ldur            x2, [fp, #-0x18]
    // 0x460d2c: ldur            x3, [fp, #-0x10]
    // 0x460d30: mov             x5, x0
    // 0x460d34: r0 = _set()
    //     0x460d34: bl              #0x3d7398  ; [dart:_compact_hash] __Map&_HashVMBase&MapMixin&_HashBase&_OperatorEqualsAndHashCode&_LinkedHashMapMixin::_set
    // 0x460d38: r0 = Null
    //     0x460d38: mov             x0, NULL
    // 0x460d3c: LeaveFrame
    //     0x460d3c: mov             SP, fp
    //     0x460d40: ldp             fp, lr, [SP], #0x10
    // 0x460d44: ret
    //     0x460d44: ret             
    // 0x460d48: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460d48: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460d4c: b               #0x460c98
  }
  static Map<String, Logger> _loggers() {
    // ** addr: 0x460d5c, size: 0x3c
    // 0x460d5c: EnterFrame
    //     0x460d5c: stp             fp, lr, [SP, #-0x10]!
    //     0x460d60: mov             fp, SP
    // 0x460d64: AllocStack(0x10)
    //     0x460d64: sub             SP, SP, #0x10
    // 0x460d68: CheckStackOverflow
    //     0x460d68: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x460d6c: cmp             SP, x16
    //     0x460d70: b.ls            #0x460d90
    // 0x460d74: r16 = <String, Logger>
    //     0x460d74: ldr             x16, [PP, #0x2e60]  ; [pp+0x2e60] TypeArguments: <String, Logger>
    // 0x460d78: ldr             lr, [THR, #0xa8]  ; THR::empty_array
    // 0x460d7c: stp             lr, x16, [SP]
    // 0x460d80: r0 = Map._fromLiteral()
    //     0x460d80: bl              #0x3d907c  ; [dart:core] Map::Map._fromLiteral
    // 0x460d84: LeaveFrame
    //     0x460d84: mov             SP, fp
    //     0x460d88: ldp             fp, lr, [SP], #0x10
    // 0x460d8c: ret
    //     0x460d8c: ret             
    // 0x460d90: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x460d90: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x460d94: b               #0x460d74
  }
  _ fine(/* No info */) {
    // ** addr: 0x480184, size: 0x48
    // 0x480184: EnterFrame
    //     0x480184: stp             fp, lr, [SP, #-0x10]!
    //     0x480188: mov             fp, SP
    // 0x48018c: AllocStack(0x8)
    //     0x48018c: sub             SP, SP, #8
    // 0x480190: SetupParameters(dynamic _ /* r2 => r3 */)
    //     0x480190: mov             x3, x2
    // 0x480194: CheckStackOverflow
    //     0x480194: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x480198: cmp             SP, x16
    //     0x48019c: b.ls            #0x4801c4
    // 0x4801a0: str             NULL, [SP]
    // 0x4801a4: r2 = Instance_Level
    //     0x4801a4: ldr             x2, [PP, #0x40d0]  ; [pp+0x40d0] Obj!Level@95cf61
    // 0x4801a8: r5 = Null
    //     0x4801a8: mov             x5, NULL
    // 0x4801ac: r4 = const [0, 0x5, 0x1, 0x5, null]
    //     0x4801ac: ldr             x4, [PP, #0x568]  ; [pp+0x568] List(5) [0, 0x5, 0x1, 0x5, Null]
    // 0x4801b0: r0 = log()
    //     0x4801b0: bl              #0x4604d4  ; [package:logging/src/logger.dart] Logger::log
    // 0x4801b4: r0 = Null
    //     0x4801b4: mov             x0, NULL
    // 0x4801b8: LeaveFrame
    //     0x4801b8: mov             SP, fp
    //     0x4801bc: ldp             fp, lr, [SP], #0x10
    // 0x4801c0: ret
    //     0x4801c0: ret             
    // 0x4801c4: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x4801c4: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x4801c8: b               #0x4801a0
  }
  _ warning(/* No info */) {
    // ** addr: 0x48089c, size: 0x84
    // 0x48089c: EnterFrame
    //     0x48089c: stp             fp, lr, [SP, #-0x10]!
    //     0x4808a0: mov             fp, SP
    // 0x4808a4: AllocStack(0x8)
    //     0x4808a4: sub             SP, SP, #8
    // 0x4808a8: SetupParameters(Logger this /* r2 => r3 */, [dynamic _ = Null /* r5 */, dynamic _ = Null /* r0 */])
    //     0x4808a8: mov             x3, x2
    //     0x4808ac: ldur            w0, [x4, #0x13]
    //     0x4808b0: sub             x2, x0, #4
    //     0x4808b4: cmp             w2, #2
    //     0x4808b8: b.lt            #0x4808e0
    //     0x4808bc: add             x0, fp, w2, sxtw #2
    //     0x4808c0: ldr             x0, [x0, #8]
    //     0x4808c4: cmp             w2, #4
    //     0x4808c8: b.lt            #0x4808e4
    //     0x4808cc: add             x4, fp, w2, sxtw #2
    //     0x4808d0: ldr             x4, [x4]
    //     0x4808d4: mov             x5, x0
    //     0x4808d8: mov             x0, x4
    //     0x4808dc: b               #0x4808ec
    //     0x4808e0: mov             x0, NULL
    //     0x4808e4: mov             x5, x0
    //     0x4808e8: mov             x0, NULL
    // 0x4808ec: CheckStackOverflow
    //     0x4808ec: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x4808f0: cmp             SP, x16
    //     0x4808f4: b.ls            #0x480918
    // 0x4808f8: str             x0, [SP]
    // 0x4808fc: r2 = Instance_Level
    //     0x4808fc: ldr             x2, [PP, #0x2e10]  ; [pp+0x2e10] Obj!Level@95cf81
    // 0x480900: r4 = const [0, 0x5, 0x1, 0x5, null]
    //     0x480900: ldr             x4, [PP, #0x568]  ; [pp+0x568] List(5) [0, 0x5, 0x1, 0x5, Null]
    // 0x480904: r0 = log()
    //     0x480904: bl              #0x4604d4  ; [package:logging/src/logger.dart] Logger::log
    // 0x480908: r0 = Null
    //     0x480908: mov             x0, NULL
    // 0x48090c: LeaveFrame
    //     0x48090c: mov             SP, fp
    //     0x480910: ldp             fp, lr, [SP], #0x10
    // 0x480914: ret
    //     0x480914: ret             
    // 0x480918: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x480918: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x48091c: b               #0x4808f8
  }
  _ finest(/* No info */) {
    // ** addr: 0x480a4c, size: 0x48
    // 0x480a4c: EnterFrame
    //     0x480a4c: stp             fp, lr, [SP, #-0x10]!
    //     0x480a50: mov             fp, SP
    // 0x480a54: AllocStack(0x8)
    //     0x480a54: sub             SP, SP, #8
    // 0x480a58: SetupParameters(dynamic _ /* r2 => r3 */)
    //     0x480a58: mov             x3, x2
    // 0x480a5c: CheckStackOverflow
    //     0x480a5c: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x480a60: cmp             SP, x16
    //     0x480a64: b.ls            #0x480a8c
    // 0x480a68: str             NULL, [SP]
    // 0x480a6c: r2 = Instance_Level
    //     0x480a6c: ldr             x2, [PP, #0x3ba8]  ; [pp+0x3ba8] Obj!Level@95cf41
    // 0x480a70: r5 = Null
    //     0x480a70: mov             x5, NULL
    // 0x480a74: r4 = const [0, 0x5, 0x1, 0x5, null]
    //     0x480a74: ldr             x4, [PP, #0x568]  ; [pp+0x568] List(5) [0, 0x5, 0x1, 0x5, Null]
    // 0x480a78: r0 = log()
    //     0x480a78: bl              #0x4604d4  ; [package:logging/src/logger.dart] Logger::log
    // 0x480a7c: r0 = Null
    //     0x480a7c: mov             x0, NULL
    // 0x480a80: LeaveFrame
    //     0x480a80: mov             SP, fp
    //     0x480a84: ldp             fp, lr, [SP], #0x10
    // 0x480a88: ret
    //     0x480a88: ret             
    // 0x480a8c: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x480a8c: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x480a90: b               #0x480a68
  }
  _ finer(/* No info */) {
    // ** addr: 0x48cb60, size: 0x48
    // 0x48cb60: EnterFrame
    //     0x48cb60: stp             fp, lr, [SP, #-0x10]!
    //     0x48cb64: mov             fp, SP
    // 0x48cb68: AllocStack(0x8)
    //     0x48cb68: sub             SP, SP, #8
    // 0x48cb6c: SetupParameters(dynamic _ /* r2 => r3 */)
    //     0x48cb6c: mov             x3, x2
    // 0x48cb70: CheckStackOverflow
    //     0x48cb70: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x48cb74: cmp             SP, x16
    //     0x48cb78: b.ls            #0x48cba0
    // 0x48cb7c: str             NULL, [SP]
    // 0x48cb80: r2 = Instance_Level
    //     0x48cb80: ldr             x2, [PP, #0x40c8]  ; [pp+0x40c8] Obj!Level@95cfa1
    // 0x48cb84: r5 = Null
    //     0x48cb84: mov             x5, NULL
    // 0x48cb88: r4 = const [0, 0x5, 0x1, 0x5, null]
    //     0x48cb88: ldr             x4, [PP, #0x568]  ; [pp+0x568] List(5) [0, 0x5, 0x1, 0x5, Null]
    // 0x48cb8c: r0 = log()
    //     0x48cb8c: bl              #0x4604d4  ; [package:logging/src/logger.dart] Logger::log
    // 0x48cb90: r0 = Null
    //     0x48cb90: mov             x0, NULL
    // 0x48cb94: LeaveFrame
    //     0x48cb94: mov             SP, fp
    //     0x48cb98: ldp             fp, lr, [SP], #0x10
    // 0x48cb9c: ret
    //     0x48cb9c: ret             
    // 0x48cba0: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x48cba0: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x48cba4: b               #0x48cb7c
  }
  _ info(/* No info */) {
    // ** addr: 0x910c24, size: 0x48
    // 0x910c24: EnterFrame
    //     0x910c24: stp             fp, lr, [SP, #-0x10]!
    //     0x910c28: mov             fp, SP
    // 0x910c2c: AllocStack(0x8)
    //     0x910c2c: sub             SP, SP, #8
    // 0x910c30: SetupParameters(dynamic _ /* r2 => r3 */)
    //     0x910c30: mov             x3, x2
    // 0x910c34: CheckStackOverflow
    //     0x910c34: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x910c38: cmp             SP, x16
    //     0x910c3c: b.ls            #0x910c64
    // 0x910c40: str             NULL, [SP]
    // 0x910c44: r2 = Instance_Level
    //     0x910c44: ldr             x2, [PP, #0x2e78]  ; [pp+0x2e78] Obj!Level@95cf01
    // 0x910c48: r5 = Null
    //     0x910c48: mov             x5, NULL
    // 0x910c4c: r4 = const [0, 0x5, 0x1, 0x5, null]
    //     0x910c4c: ldr             x4, [PP, #0x568]  ; [pp+0x568] List(5) [0, 0x5, 0x1, 0x5, Null]
    // 0x910c50: r0 = log()
    //     0x910c50: bl              #0x4604d4  ; [package:logging/src/logger.dart] Logger::log
    // 0x910c54: r0 = Null
    //     0x910c54: mov             x0, NULL
    // 0x910c58: LeaveFrame
    //     0x910c58: mov             SP, fp
    //     0x910c5c: ldp             fp, lr, [SP], #0x10
    // 0x910c60: ret
    //     0x910c60: ret             
    // 0x910c64: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x910c64: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x910c68: b               #0x910c40
  }
  _ config(/* No info */) {
    // ** addr: 0x93e550, size: 0x48
    // 0x93e550: EnterFrame
    //     0x93e550: stp             fp, lr, [SP, #-0x10]!
    //     0x93e554: mov             fp, SP
    // 0x93e558: AllocStack(0x8)
    //     0x93e558: sub             SP, SP, #8
    // 0x93e55c: SetupParameters(dynamic _ /* r2 => r3 */)
    //     0x93e55c: mov             x3, x2
    // 0x93e560: CheckStackOverflow
    //     0x93e560: ldr             x16, [THR, #0x48]  ; THR::stack_limit
    //     0x93e564: cmp             SP, x16
    //     0x93e568: b.ls            #0x93e590
    // 0x93e56c: str             NULL, [SP]
    // 0x93e570: r2 = Instance_Level
    //     0x93e570: ldr             x2, [PP, #0x65b0]  ; [pp+0x65b0] Obj!Level@95cfc1
    // 0x93e574: r5 = Null
    //     0x93e574: mov             x5, NULL
    // 0x93e578: r4 = const [0, 0x5, 0x1, 0x5, null]
    //     0x93e578: ldr             x4, [PP, #0x568]  ; [pp+0x568] List(5) [0, 0x5, 0x1, 0x5, Null]
    // 0x93e57c: r0 = log()
    //     0x93e57c: bl              #0x4604d4  ; [package:logging/src/logger.dart] Logger::log
    // 0x93e580: r0 = Null
    //     0x93e580: mov             x0, NULL
    // 0x93e584: LeaveFrame
    //     0x93e584: mov             SP, fp
    //     0x93e588: ldp             fp, lr, [SP], #0x10
    // 0x93e58c: ret
    //     0x93e58c: ret             
    // 0x93e590: r0 = StackOverflowSharedWithoutFPURegs()
    //     0x93e590: bl              #0x935cd0  ; StackOverflowSharedWithoutFPURegsStub
    // 0x93e594: b               #0x93e56c
  }
}
