import type { Appliance, ComponentLibrary, SystemSettings } from './types'

export const suppliedComponentLibrary: ComponentLibrary = {
  inverters: [{
    id: 'supplied-inverter-11kw-48v',
    name: '11 kW / 48 V (datasheet)',
    systemVoltage: 48,
    inverterRatedWatts: 11000,
    inverterSurgeWattsRating: 22000,
    inverterEfficiency: 0.93,
    maxSolarChargeCurrent: 150,
    maxAcChargeCurrent: 150,
    maxTotalChargeCurrent: 150,
    inverterMaxPvWatts: 11000,
    mpptMinVoltage: 90,
    mpptMaxVoltage: 450,
    maxPvOpenCircuitVoltage: 500,
    maxPvInputCurrentPerMppt: 18,
    maxPvShortCircuitCurrentPerMppt: Number.NaN,
    mpptCount: 2,
    inverterFloatChargeVoltage: 54,
    inverterOverchargeProtectionVoltage: 63,
  }],
  panels: [{
    id: 'supplied-panel-jinko-jkm590n-78hl4-bdv',
    name: 'Jinko JKM590N-78HL4-BDV',
    panelWatts: 590,
    panelVmp: 44.91,
    panelVoc: 54.76,
    panelIsc: 13.71,
    panelImp: 13.14,
    panelVocTemperatureCoefficientPercent: -0.25,
    // The datasheet does not publish a Vmp coefficient. The calculator derives
    // a provisional value from beta(Pmax) - alpha(Isc) and labels it as derived.
    panelPmaxTemperatureCoefficientPercent: -0.30,
    panelIscTemperatureCoefficientPercent: 0.046,
  }],
  batteries: [{
    id: 'supplied-battery-hespro-lbs-51-2-300',
    name: 'Swift HESPRO LBS 51.2-300',
    batteryVoltage: 51.2,
    batteryMinVoltage: 48,
    batteryMaxVoltage: 57.6,
    batteryAh: 300,
    batteryMaxChargeCurrent: 100,
    depthOfDischarge: 0.95,
    batteryMaxDischargeCurrent: 100,
    batterySurgeDischargeCurrent: 300,
    batterySurgeDurationSeconds: 30,
    batteryMaxParallelUnits: 15,
  }],
}

export const defaultSettings: SystemSettings = {
  inverterModelName: '',
  panelModelName: '',
  batteryModelName: '',
  systemVoltage: 24,
  peakSunHours: 6,
  panelWatts: 590,
  panelVmp: 42.2,
  panelVoc: 50.4,
  panelIsc: 14.1,
  panelImp: 13.98,
  panelVocTemperatureCoefficientPercent: -0.25,
  panelVmpTemperatureCoefficientPercent: -0.29,
  panelPmaxTemperatureCoefficientPercent: -0.27,
  panelIscTemperatureCoefficientPercent: 0.045,
  minimumSiteTemperatureC: 0,
  designCellTemperatureC: 45,
  arrayTiltDegrees: Number.NaN,
  arrayAzimuthDegrees: Number.NaN,
  batteryVoltage: 12,
  batteryMinVoltage: 10.5,
  batteryMaxVoltage: 14.6,
  batteryAh: 200,
  depthOfDischarge: 0.8,
  autonomyDays: 2,
  lossPercent: 35,
  soilingLossPercent: Number.NaN,
  shadingLossPercent: Number.NaN,
  mismatchLossPercent: Number.NaN,
  wiringLossPercent: Number.NaN,
  availabilityLossPercent: Number.NaN,
  orientationLossPercent: Number.NaN,
  safetyFactor: 1.2,
  controllerEfficiency: 0.95,
  inverterEfficiency: 0.9,
  batteryChargeEfficiency: 0.95,
  batteryDischargeEfficiency: 0.95,
  batteryAgingFactor: 0.9,
  inverterRatedWatts: Number.NaN,
  inverterSurgeWattsRating: Number.NaN,
  maxSolarChargeCurrent: 100,
  maxAcChargeCurrent: 60,
  maxTotalChargeCurrent: 100,
  batteryMaxChargeCurrent: 100,
  batteryMaxDischargeCurrent: 100,
  batterySurgeDischargeCurrent: 300,
  batterySurgeDurationSeconds: 30,
  batteryMaxParallelUnits: 15,
  inverterMaxPvWatts: 4000,
  mpptMinVoltage: 120,
  mpptMaxVoltage: 430,
  maxPvOpenCircuitVoltage: 500,
  maxPvInputCurrentPerMppt: 18,
  maxPvShortCircuitCurrentPerMppt: Number.NaN,
  mpptCount: 1,
  inverterFloatChargeVoltage: Number.NaN,
  inverterOverchargeProtectionVoltage: Number.NaN,
}

export const createEmptySettings = (): SystemSettings => ({
  inverterModelName: '',
  panelModelName: '',
  batteryModelName: '',
  systemVoltage: Number.NaN,
  peakSunHours: Number.NaN,
  panelWatts: Number.NaN,
  panelVmp: Number.NaN,
  panelVoc: Number.NaN,
  panelIsc: Number.NaN,
  panelImp: Number.NaN,
  panelVocTemperatureCoefficientPercent: Number.NaN,
  panelVmpTemperatureCoefficientPercent: Number.NaN,
  panelPmaxTemperatureCoefficientPercent: Number.NaN,
  panelIscTemperatureCoefficientPercent: Number.NaN,
  minimumSiteTemperatureC: Number.NaN,
  designCellTemperatureC: Number.NaN,
  arrayTiltDegrees: Number.NaN,
  arrayAzimuthDegrees: Number.NaN,
  batteryVoltage: Number.NaN,
  batteryMinVoltage: Number.NaN,
  batteryMaxVoltage: Number.NaN,
  batteryAh: Number.NaN,
  depthOfDischarge: Number.NaN,
  autonomyDays: Number.NaN,
  lossPercent: Number.NaN,
  soilingLossPercent: Number.NaN,
  shadingLossPercent: Number.NaN,
  mismatchLossPercent: Number.NaN,
  wiringLossPercent: Number.NaN,
  availabilityLossPercent: Number.NaN,
  orientationLossPercent: Number.NaN,
  safetyFactor: Number.NaN,
  controllerEfficiency: 0.95,
  inverterEfficiency: Number.NaN,
  batteryChargeEfficiency: Number.NaN,
  batteryDischargeEfficiency: Number.NaN,
  batteryAgingFactor: Number.NaN,
  inverterRatedWatts: Number.NaN,
  inverterSurgeWattsRating: Number.NaN,
  maxSolarChargeCurrent: Number.NaN,
  maxAcChargeCurrent: Number.NaN,
  maxTotalChargeCurrent: Number.NaN,
  batteryMaxChargeCurrent: Number.NaN,
  batteryMaxDischargeCurrent: Number.NaN,
  batterySurgeDischargeCurrent: Number.NaN,
  batterySurgeDurationSeconds: Number.NaN,
  batteryMaxParallelUnits: Number.NaN,
  inverterMaxPvWatts: Number.NaN,
  mpptMinVoltage: Number.NaN,
  mpptMaxVoltage: Number.NaN,
  maxPvOpenCircuitVoltage: Number.NaN,
  maxPvInputCurrentPerMppt: Number.NaN,
  maxPvShortCircuitCurrentPerMppt: Number.NaN,
  mpptCount: Number.NaN,
  inverterFloatChargeVoltage: Number.NaN,
  inverterOverchargeProtectionVoltage: Number.NaN,
})

export const createEmptyAppliances = (): Appliance[] => [{
  id: crypto.randomUUID(),
  name: '',
  dayQuantity: Number.NaN,
  nightQuantity: Number.NaN,
  watts: Number.NaN,
  dayHours: Number.NaN,
  nightHours: Number.NaN,
  dutyCycle: 1,
  measuredDayEnergyWh: Number.NaN,
  measuredNightEnergyWh: Number.NaN,
  surgeFactor: Number.NaN,
  startGroup: 1,
  critical: false,
  enabled: true,
}]

export const defaultAppliances: Appliance[] = [
  {
    id: 'mixer',
    name: 'خلاط ماء',
    dayQuantity: 2,
    nightQuantity: 2,
    watts: 150,
    dayHours: 12,
    nightHours: 0,
    dutyCycle: 1,
    surgeFactor: 1.5,
    startGroup: 1,
    critical: false,
    enabled: true,
  },
  {
    id: 'fridge',
    name: 'ثلاجة',
    dayQuantity: 2,
    nightQuantity: 2,
    watts: 250,
    dayHours: 6,
    nightHours: 6,
    dutyCycle: 1,
    surgeFactor: 5,
    enabled: true,
  },
  {
    id: 'spare',
    name: '',
    dayQuantity: 1,
    nightQuantity: 1,
    watts: 0,
    dayHours: 0,
    nightHours: 0,
    dutyCycle: 1,
    surgeFactor: 1,
    enabled: true,
  },
]

export const inverterSizes = [500, 800, 1000, 1500, 2000, 3000, 5000, 6000, 8000, 10000, 12000, 15000]
